const ProductItemList = [
  {
    id: crypto.randomUUID(),
    title: "Gradient Graphic T-shirt",
    price: 145,
    imageUrl: "c.png",
    rating: 5,
    quantity: 10,
    isAdded: false,
    size: "Large",
    color: "White",
  },
  {
    id: crypto.randomUUID(),
    title: "Gradient Graphic T-shirt",
    price: 145,
    imageUrl: "image 1.png",
    rating: 4,
    quantity: 212,
    isAdded: false,
    size: "Large",
    color: "White",
  },
  {
    id: crypto.randomUUID(),
    title: "Polo with Tipping Details",
    price: 180,
    imageUrl: "image 7.png",
    rating: 1,
    quantity: 320,
    isAdded: false,
    size: "Medium",
    color: "Black",
  },
  {
    id: crypto.randomUUID(),
    title: "Black Striped T-shirt",
    price: 100,
    imageUrl: "image 8-1.png",
    rating: 3,
    quantity: 120,
    isAdded: false,
    size: "Small",
    color: "Yellow",
  },
  {
    id: crypto.randomUUID(),
    title: "Skinny Fit Jeans",
    price: 240,
    imageUrl: "image 8-2.png",
    rating: 2,
    quantity: 240,
    isAdded: false,
    size: "Large",
    color: "White",
  },
  {
    id: crypto.randomUUID(),
    title: "Checkered Shirt",
    price: 180,
    imageUrl: "image 8.png",
    rating: 5,
    quantity: 20,
    isAdded: false,
    size: "Large",
    color: "White",
  },
  {
    id: crypto.randomUUID(),
    title: "Sleeve Striped T-shirt",
    price: 13,
    imageUrl: "image 9-1.png",
    rating: 4,
    quantity: 20,
    isAdded: false,
    size: "Large",
    color: "White",
  },
  {
    id: crypto.randomUUID(),
    title: "Vertical Striped Shirt",
    price: 100,
    imageUrl: "image 9-2.png",
    rating: 4,
    quantity: 212,
    isAdded: false,
    size: "Large",
    color: "White",
  },
  {
    id: crypto.randomUUID(),
    title: "Courage Graphic T-shirt",
    price: 100,
    imageUrl: "image 9.png",
    rating: 4,
    quantity: 212,
    isAdded: false,
    size: "Large",
    color: "White",
  },
  {
    id: crypto.randomUUID(),
    title: "Loose Fit Bermuda Shorts",
    price: 100,
    imageUrl: "image 10-1.png",
    rating: 4,
    quantity: 212,
    isAdded: false,
    size: "Large",
    color: "White",
  },
  {
    id: crypto.randomUUID(),
    title: "Gradient Graphic T-shirt",
    price: 100,
    imageUrl: "image 10-2.png",
    rating: 4,
    quantity: 212,
    isAdded: false,
    size: "Large",
    color: "White",
  },
  {
    id: crypto.randomUUID(),
    title: "Gradient Graphic T-shirt",
    price: 100,
    imageUrl: "image 10.png",
    rating: 4,
    quantity: 212,
    isAdded: false,
    size: "Large",
    color: "White",
  },
];

export default ProductItemList;
